# Generated by Django 5.0.6 on 2024-05-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("genre_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adult", models.BooleanField(default=False)),
                ("backdrop_path", models.CharField(max_length=100, null=True)),
                ("movie_id", models.IntegerField(unique=True)),
                ("original_language", models.CharField(max_length=10)),
                ("original_title", models.CharField(max_length=100)),
                ("overview", models.TextField(null=True)),
                ("popularity", models.FloatField(null=True)),
                ("poster_path", models.CharField(max_length=100)),
                ("release_date", models.DateField(null=True)),
                ("title", models.CharField(max_length=100)),
                ("vote_average", models.FloatField(default=0, null=True)),
                ("vote_count", models.IntegerField(default=0, null=True)),
                ("genre_ids", models.ManyToManyField(to="movieapp.genre")),
            ],
        ),
    ]
